VAR totalInteractions = 0
VAR currentHat = 5
VAR setQuestText = ""
VAR sinkTurned = false
VAR fridgeOpen = false
VAR hat_text = "Many hats sit before you, begging to be worn."
VAR awaken = false
VAR sinkFix = false
VAR love = 0
VAR waterTemp = ""
VAR sinkRunning = false
VAR drank = 0